### ISSUE TITLE
Username is not restricted

### ISSUE THREAD

**Issue by jjohnsto** [CMPUT301F15T14/AndroidDesignProject#37]
Currently, the username field in EditProfileActivity has no restrictions. This allows the user to create a very long user name with the possibility of adding spaces. This should be fixed so that it is constrained for size and doesn't allow spaces.

**Comment by kobitoko** [comment]
I did it. made it same restricted to 14 characters. and google-mail-valid-characters only

**Comment by kobitoko** [comment]
I did it. made it same restricted to 14 characters. and google-mail-valid-characters only
