### ISSUE TITLE
Have issue loading from JSON in InventoryListActivity

### ISSUE THREAD

**Issue by bcvancouver** [CMPUT301F15T14/AndroidDesignProject#56]
Caused by: java.lang.RuntimeException: InventoryListActivity was not passed a user

Actual Code:
mainUser = (User)ObjParseSingleton.getInstance().popObject("User");
        if(mainUser == null) {
            throw new RuntimeException("InventoryListActivity was not passed a user");
        }

**Comment by kobitoko** [comment]
kinda solved with https://github.com/CMPUT301F15T14/AndroidDesignProject/commit/3c29140b829b84f92e09bdb44e256f090a34c0fb

It is very rare, and usually due to a crash from an activity after it? 
so instead of force crash i made it finish() current activity and return; 
A "soft-crash" as you will.
