### ISSUE TITLE
Friends list doesn't save

### ISSUE THREAD

**Issue by jjohnsto** [CMPUT301F15T14/AndroidDesignProject#70]
I've attempted using our File IO code to get this working but the Friends list is lost upon closing the app. Might have something to do with the way the user singleton is loaded.

**Comment by kobitoko** [comment]
Fixed with https://github.com/CMPUT301F15T14/AndroidDesignProject/commit/9fc3a08c8179cf6ae759accde8bb1615d395e0e5
