### ISSUE TITLE
Poor color scheme

### ISSUE THREAD

**Issue by jjohnsto** [CMPUT301F15T14/AndroidDesignProject#71]
The choice of high contrast colors is a bit of an eyesore. A different choice of theme and color selection is needed to improve legibility and aesthetic quality.

**Comment by kobitoko** [comment]
Changed it a bit with https://github.com/CMPUT301F15T14/AndroidDesignProject/commit/6a56a912dfccad861b5808b5ed1ab92a98b83f96

so background is darker, and all/most text is white.
Legibility is ok i think.
Aesthetics still questionable lol.

**Comment by jjohnsto** [comment]
Messed around a bit with the theme and background. Looks more professional now.
