### ISSUE TITLE
TradeHistoryActivity no longer displays trades

### ISSUE THREAD

**Issue by Belzet** [CMPUT301F15T14/AndroidDesignProject#76]
You can create a trade but it will no longer appear listed in TradeHistoryActivity. Sometimes you can catch a flash of it before it disappears.

**Comment by kobitoko** [comment]
Fixed with https://github.com/CMPUT301F15T14/AndroidDesignProject/commit/15e7998bf367b6edea49622f803a60fe5ee04ada
